import { useEffect, useState } from "react";
import { useAuth } from "../context/AuthContext";
import { C, buttonStyle, labelStyle, cardStyle } from "../styles/theme";
import FormInput from "../components/FormInput";
import { ErrorBox } from "../components/MessageBox";
import Logo from "../components/Logo";

// Same 8-digit numeric password rule as the original app. Firebase Auth
// itself only enforces a 6-character minimum, so this app-level rule is
// what actually keeps passwords consistent with the old design intent.
const PASSWORD_RULE = /^\d{8}$/;
const EMAIL_RULE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export default function AuthPage() {
  const { login, register } = useAuth();
  const [mode, setMode] = useState("login");
  const [form, setForm] = useState({ name: "", email: "", password: "", phone: "", refCode: "" });
  const [showPw, setShowPw] = useState(false);
  const [err, setErr] = useState("");
  const [busy, setBusy] = useState(false);

  // FIXED this session: a referral link (?ref=CODE, generated by
  // ReferralsPage.jsx) was never actually read back out here — the field
  // always started empty regardless of which link was used to arrive at
  // this page, silently breaking the referral flow for anyone using a
  // shared link rather than manually typing a code. Also switches
  // straight to the registration form when a ref code is present, since
  // landing on the LOGIN screen (where the referral field isn't even
  // shown) is the wrong default for someone who just clicked a referral
  // link — they're a prospective new signup, not a returning user.
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const refFromLink = params.get("ref");
    if (refFromLink) {
      setForm((f) => ({ ...f, refCode: refFromLink.trim().toUpperCase() }));
      setMode("register");
    }
  }, []);

  const set = (key) => (e) => setForm((f) => ({ ...f, [key]: e.target.value }));

  async function handleSubmit(e) {
    e.preventDefault();
    setErr("");

    if (mode === "register") {
      if (!form.name.trim()) return setErr("Please enter your full name.");
      if (!EMAIL_RULE.test(form.email)) return setErr("Please enter a valid email address.");
      if (!form.phone.trim()) return setErr("Please enter your phone number.");
      if (!PASSWORD_RULE.test(form.password)) return setErr("Password must be exactly 8 numbers, e.g. 12345678.");

      setBusy(true);
      try {
        await register({
          name: form.name.trim(),
          email: form.email.trim(),
          password: form.password,
          phone: form.phone.trim(),
          refCode: form.refCode.trim(),
        });
      } catch (e2) {
        console.error(e2);
        setErr("Something went wrong. Please try again.");
      }
      setBusy(false);
    } else {
      if (!EMAIL_RULE.test(form.email)) return setErr("Please enter a valid email address.");
      if (!form.password) return setErr("Please enter your password.");

      setBusy(true);
      try {
        await login(form.email.trim(), form.password);
      } catch (e2) {
        console.error(e2);
        setErr("Invalid email or password.");
      }
      setBusy(false);
    }
  }

  return (
    <div
      style={{
        minHeight: "100vh",
        background: C.bg,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: 16,
      }}
    >
      <div
        style={{
          width: "100%",
          maxWidth: 440,
          background: cardStyle.background,
          border: `1px solid ${C.gold}30`,
          borderRadius: 20,
          padding: "44px 28px",
          backdropFilter: "blur(20px)",
          boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
        }}
        className="fade"
      >
        <div style={{ marginBottom: 28, display: "flex", justifyContent: "center" }}>
          <Logo size={36} />
        </div>
        <h1
          style={{
            fontSize: 24,
            fontWeight: 800,
            color: C.gold,
            textAlign: "center",
            marginBottom: 6,
          }}
        >
          {mode === "register" ? "Create account" : "Welcome back"}
        </h1>
        <p style={{ fontSize: 14, color: C.muted, marginBottom: 28, textAlign: "center", fontWeight: 600 }}>
          {mode === "register" ? "Start growing your wealth today" : "Sign in to continue"}
        </p>

        {err && <ErrorBox>{err}</ErrorBox>}

        <form onSubmit={handleSubmit}>
          {mode === "register" && (
            <div style={{ marginBottom: 18 }}>
              <label style={labelStyle}>Full Name</label>
              <FormInput value={form.name} onChange={set("name")} placeholder="e.g. Chidinma Okafor" />
            </div>
          )}

          {mode === "register" && (
            <div style={{ marginBottom: 18 }}>
              <label style={labelStyle}>Phone Number</label>
              <FormInput value={form.phone} onChange={set("phone")} placeholder="e.g. 08012345678" />
            </div>
          )}

          <div style={{ marginBottom: 18 }}>
            <label style={labelStyle}>Email Address</label>
            <FormInput type="email" value={form.email} onChange={set("email")} placeholder="you@example.com" />
          </div>

          <div style={{ marginBottom: mode === "register" ? 18 : 8 }}>
            <label style={labelStyle}>{mode === "register" ? "Password (8 digits)" : "Password"}</label>
            <div style={{ position: "relative" }}>
              <FormInput
                type={showPw ? "text" : "password"}
                value={form.password}
                onChange={set("password")}
                placeholder={mode === "register" ? "12345678" : "Your password"}
              />
              <button
                type="button"
                onClick={() => setShowPw((s) => !s)}
                style={{
                  position: "absolute",
                  right: 14,
                  top: "50%",
                  transform: "translateY(-50%)",
                  background: "none",
                  border: "none",
                  color: C.dim,
                  cursor: "pointer",
                  fontSize: 18,
                  minHeight: "auto",
                }}
              >
                {showPw ? "🙈" : "👁"}
              </button>
            </div>
            {mode === "register" && (
              <p style={{ fontSize: 11, color: C.dim, marginTop: 6 }}>Must be exactly 8 numbers e.g. 12345678</p>
            )}
          </div>

          {mode === "register" && (
            <div style={{ marginBottom: 24 }}>
              <label style={labelStyle}>Referral Code (Optional)</label>
              <FormInput placeholder="e.g. JOHN4X9K" value={form.refCode} onChange={set("refCode")} />
            </div>
          )}

          <button type="submit" disabled={busy} style={{ ...buttonStyle("gold"), width: "100%", marginTop: mode === "login" ? 16 : 0 }}>
            {busy ? "Please wait…" : mode === "register" ? "Create Account" : "Sign In"}
          </button>
        </form>

        <div style={{ textAlign: "center", marginTop: 16, fontSize: 13, color: C.muted }}>
          {mode === "register" ? "Have one? " : "New here? "}
          <button
            type="button"
            style={{ background: "none", border: "none", color: C.emerald, cursor: "pointer", fontSize: 13 }}
            onClick={() => {
              setMode(mode === "register" ? "login" : "register");
              setErr("");
            }}
          >
            {mode === "register" ? "Sign in" : "Create account"}
          </button>
        </div>
      </div>

      {/* Builder credit — per the site owner's explicit request, visible
          on the very first screen a user sees, not just buried in
          Settings. Kept small/subtle so it doesn't compete with the
          sign-in/register form itself. */}
      <a
        href="https://wa.me/18455713692"
        target="_blank"
        rel="noopener noreferrer"
        style={{
          marginTop: 20,
          fontSize: 11.5,
          color: C.dim,
          textDecoration: "none",
          fontWeight: 600,
        }}
      >
        Built by High 5ive Digitals
      </a>
    </div>
  );
}
